FROM microsoft/dotnet:2.2-sdk
WORKDIR /app

# copy both folders to make sure the test has access to them both, just like in development mode
COPY API ./API
COPY TEST ./TEST

# Restore and then run the tests once
RUN dotnet restore TEST
RUN dotnet test TEST

# Restore the mini-api  and then run it
RUN dotnet restore API
RUN dotnet publish API -c Release -o out
ENTRYPOINT ["dotnet", "API/out/API.dll"]